apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: medichannel
spec:
  selector:
    app: ai-service
  ports:
    - port: 5008
      targetPort: 5008
      nodePort: 30018
  type: NodePort