apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: medichannel
spec:
  selector:
    app: doctor-service
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010
  type: NodePort