apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: medichannel
spec:
  selector:
    app: notification-service
  ports:
    - port: 5007
      targetPort: 5007
  type: ClusterIP