apiVersion: v1
kind: Service
metadata:
  name: prescription-service
  namespace: medichannel
spec:
  selector:
    app: prescription-service
  ports:
    - port: 5006
      targetPort: 5006
      nodePort: 30016
  type: NodePort