apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medichannel
spec:
  selector:
    app: auth-service
  ports:
    - name: public
      port: 5001
      targetPort: 5001
    - name: internal
      port: 5011
      targetPort: 5011
  type: ClusterIP
