apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: medichannel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: kswijesinghe/appointment-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: AUTH_INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AUTH_INTERNAL_SECRET
            - name: AUTH_INTERNAL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AUTH_INTERNAL_SERVICE_URL
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: APPOINTMENT_MONGO_URI
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AUTH_SERVICE_URL
            - name: DOCTOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DOCTOR_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NOTIFICATION_SERVICE_URL
            - name: TELEMEDICINE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: TELEMEDICINE_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SERVICE_SECRET