apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: medichannel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: kswijesinghe/telemedicine-service:latest
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: TELEMEDICINE_MONGO_URI
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: APPOINTMENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NOTIFICATION_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SERVICE_SECRET