apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: medichannel
spec:
  selector:
    app: telemedicine-service
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30014
  type: NodePort