apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: medichannel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: kswijesinghe/patient-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: AUTH_INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AUTH_INTERNAL_SECRET
            - name: AUTH_INTERNAL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AUTH_INTERNAL_SERVICE_URL
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: PATIENT_MONGO_URI
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: AUTH_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_REPORTS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CLOUDINARY_REPORTS_FOLDER