apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: medichannel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: kswijesinghe/payment-service:latest
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: PAYMENT_MONGO_URI
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: APPOINTMENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NOTIFICATION_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SERVICE_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: STRIPE_WEBHOOK_SECRET