apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: medichannel
spec:
  selector:
    app: payment-service
  ports:
    - port: 5005
      targetPort: 5005
      nodePort: 30015
  type: NodePort